### ISSUE TITLE
loadstatic_django.apps.coreconfig.name is correct or not.

### ISSUE THREAD

**Issue by SwagataRoy98** [vBlackOut/loadstatic-django#1]
![image](https://user-images.githubusercontent.com/72523574/230767027-4d4295c6-e60a-4e20-90b7-fc3cae590d6e.png)
It seems app label is not correctly configured/

**Comment by vBlackOut** [comment]
Hello ok i try to change this name inside apps.py loadstatic-django ?
name = 'app.core' to
name = "loadstatic-django" try that


ok i found one solution work 

move your directory inside sites-package "loadstatic-django" to "loadstatic_django" and rename your apps.py inside this package 
name = "loadstatic_django"

and inside your settings.py change your INSTALL_APP by loadstatic_django and retry it's minor bug name package
i try to fix inside the pip version 

thank for your issue

try that now : 

git clone https://github.com/vBlackOut/loadstatic-django
cd loadstatic-django
python3 setup.py install 

and reback inside your projet ? it's work

**Comment by SwagataRoy98** [comment]
It works!!! Thanks very much for replying..
